### ISSUE TITLE
Missing Kicad Libraries

### ISSUE THREAD

**Issue by Helder1981** [marqs85/snes_dejitter#1]
Hello I tried to open the schematic and got these 2 errors:

**The following libraries were not found:**
snes_dejitter-rescue
motors

Is there anyway you can also have a BOM list to build the board and any chance you can make this in Eagle CAD?

Thanks.

**Comment by marqs85** [comment]
BOM is added in facaa83. You should be able to ignore missing library errors as long as no components are actually used from them (like in case of those 2).

As for redoing the board in Eagle, it's a bit tall order considering required work versus benefits. There should be some conversion tools avaiable for those who want to import the design into Eagle, and many of those who want to integrate functionality into their design will probably want to make own schematics and layout anyway.
