### ISSUE TITLE
NES-001 Everdrive N8 crash

### ISSUE THREAD

**Issue by matjolic** [marqs85/snes_dejitter#3]
I installed the dejitter board in a NESRGB modded NES-001. I get this weird behavior where the game hangs either a few minutes in or at the loading screen and sometimes even resets the Everdrive N8. If I remove the dejitter board, the same game runs fine. Specifically, I was trying an expansion audio game, VRC6 Akumajou Densetsu. I haven't tried the comparison with other games, but I was able to replicate this behavior on a second system. I've tried both the original firmware and the nes-fix firmware. Is the N8 somehow relying on the original crystal? Does expansion audio rely on it? I am not savvy enough to answer these questions, can someone replicate this?

**Comment by marqs85** [comment]
Updated instructions with a recommendation to use coax cable (both sides grounded) for MCLK_i which should fix the issue based on posts on the forum thread.
