### ISSUE TITLE
NES-CPU-04 different PCB layout + pink flickering on composite output from NESRGB

### ISSUE THREAD

**Issue by Quantum-cross** [marqs85/snes_dejitter#5]
I'm installing the de-jitter mod on an NES-CPU-04 and I had to use a multimeter and NES schematics to figure out which wires to bridge.

![pcb](https://cdn.discordapp.com/attachments/193520586297704457/526558055245021218/IMG_20181223_1933137.jpg)

Everything seems to work right if I bridge the the points shown there (not the outside PTHs).

The only other problem I am having is the composite video output from the NESRGB has some artifacts:
![artifact](https://cdn.discordapp.com/attachments/193520586297704457/526559002637893642/untitled.PNG)

This seems to flicker every frame. This is present on an LCD tv too (not a capture problem) and RGB output also seems to work fine without that pink glitch.

**Comment by Quantum-cross** [comment]
Hey @marqs85, if you add the CPU-04 instructions I'll consider this closed. 👍 

Feel free to use the jumper wire picture above, that is the only difference.

**Comment by marqs85** [comment]
instructions added
