### ISSUE TITLE
Programming

### ISSUE THREAD

**Issue by Chris230291** [marqs85/snes_dejitter#7]
Hello. I am trying to program the chip using my clone usb blaster.
When I try to run the command this is what I am getting...

```
pi@raspberrypi:~ $ sudo openocd -f openocd/tcl/interface/altera-usb-blaster.cfg
Open On-Chip Debugger 0.10.0+dev-00430-g06123153 (2020-06-27-19:51)
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
Warn : Adapter driver 'usb_blaster' did not declare which transports it allows; assuming legacy JTAG-only
Info : only one transport option; autoselect 'jtag'
Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
Error: No lowlevel driver available
```

I am not sure what I can do to fix that.

I decided to try using the Quartus II programmer software in windows to see if that would work. I can get it to detect _something_, but its an unknown device (UNKOWN_150203F) and trying to flash using the  .pof file just gives errors.

I am supplying 5v to the board. Without it nothing is detected. I have also shorted R4.

Can anyone give me any advice. I am happy to use linux or windows. No pref

Cheers
Chris

**Comment by marqs85** [comment]
It looks like the openocd version you're using is not built with usb blaster support (check lines 149 and 866 [here](http://openocd.org/doc/doxygen/html/usb__blaster_8c_source.html)). You might want to try building it from source and enable usb blaster support during configure (./configure --enable-usb-blaster).

**Comment by Chris230291** [comment]
Thanks for the reply but I ended up just buying a ft232h which worked perfectly
