### ISSUE TITLE
CPLD Alternatives

### ISSUE THREAD

**Issue by RastaJedi** [marqs85/snes_dejitter#8]
Hi Markus!

I'm trying to build a couple of these. The ATF1502AS-7AX44 CPLD is out of stock everywhere (besides waiting from China). Is ATF1502AS-10AU44 a viable alternative? The max freq. is a tad lower, and the propagation delay is slightly longer... I don't want to mess anything up. Can you please let me know?

Thank you so much!

**Comment by marqs85** [comment]
Unfortunately ATF1502AS-10AU44 has not been tested so use it at own risk. Availability of ATF1502AS-7AX44 has been a problem recently, but Mouser & Digikey estimates indicate that it should be restocked soon.

**Comment by RastaJedi** [comment]
Thank you, kind sir!

**Comment by marqs85** [comment]
It is now stocked in Digikey.
